source 'https://rubygems.org'

ruby '2.0.0'
gem 'rails', '4.0.0'

group :development do
  gem 'quiet_assets'
end

gem 'unicorn'

group :test do
  gem 'capybara'
  gem 'factory_girl_rails'
  gem 'simplecov'
  gem 'vcr'
  gem 'webmock'
end

gem 'active_model_serializers'
gem 'activeadmin',         github: 'gregbell/active_admin', branch: 'rails4'
gem 'acts-as-taggable-on'
gem 'acts_as_commentable'
gem 'aws-s3', :require => 'aws/s3'
gem 'aws-sdk'
gem 'ckeditor'
gem 'coffee-rails'
gem 'debugger'
gem 'devise',              github: 'plataformatec/devise'
gem 'eco'
gem 'formtastic',          github: 'justinfrench/formtastic'
gem 'inherited_resources', github: 'josevalim/inherited_resources'
gem 'iron_worker_ng'
gem 'jquery-fileupload-rails'
gem 'jquery-rails'
gem 'json'
gem 'kaminari'
gem 'mini_magick'
gem 'newrelic_rpm'
gem 'omniauth'
gem 'omniauth-instagram'
gem 'paperclip'
gem 'pg'
gem 'puma'
gem 'rails-observers'
gem 'rails3_serve_static_assets', github: 'heroku/rails3_serve_static_assets'
gem 'rails_12factor',             group: :production
gem 'ransack',                    github: 'ernie/ransack', branch: 'rails-4'
gem 'responders',                 github: 'plataformatec/responders'
gem 'rspec-rails'
gem 'sass-rails'
gem 'select2-rails'
gem 'sentry-raven'
gem 'simple_form',                github: 'plataformatec/simple_form'
gem 'slim'
gem 'socialization'
gem 'spiderable'
gem 'spine-rails'
gem 'typhoeus'
gem 'uglifier'
gem 'uniquify'

